default: &default
  adapter: postgresql
  encoding: unicode
  username: myapp
  password: 1234
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: list_development

test:
  <<: *default
  database: list_test

production:
  <<: *default
  database: list_production
